### ISSUE TITLE
能否为geometry绘制添加srt参数

### ISSUE THREAD

**Issue by czlc** [ejoy/ejoy2d#82]
最近加入的geometry能否绘制的时候加入srt参数，因为我用在绘制战棋的地表阴影，需要有和sprite一样的变换

**Comment by cloudwu** [comment]
我要先看看。原本打算做 UI 的时候用。

**Comment by cloudwu** [comment]
我建议你先这样:

我猜想你是想用那个 polygon 的特性, 而 polygon 是用一个数字 table 表示的.
而 ejoy2d 已经提供了 matrix 模块, 你可以把 srt 转成一个 mat , 然后用 mat 依次乘 table 里的 vector2 就可以了.

**Comment by czlc** [comment]
谢谢，解决了
