### ISSUE TITLE
lnewlabel函数参数混乱

### ISSUE THREAD

**Issue by jintiao** [ejoy/ejoy2d#85]
https://github.com/ejoy/ejoy2d/blob/master/lib/lsprite.c#L69-L73
label.space_w = (int)lua_tointeger(L, 5);
const char \* align = lua_tostring(L,5);

**Comment by rainfiel** [comment]
fixed,  https://github.com/ejoy/ejoy2d/commit/ebb2b6146fb497d2f08a5d425686ea2deab1082d
