### ISSUE TITLE
关于sprite.ldraw中srt参数

### ISSUE THREAD

**Issue by czlc** [ejoy/ejoy2d#95]
缩放场景的时候，希望pinch的中点在缩放前后所处的屏幕位置不变(就像手机中看图片，或者coc里面缩放场景的感受)，所以先把pinch的中点平移到原点，缩放之后再移回来。但是由此得到的变换矩阵无法用srt描述，请指教。

http://stackoverflow.com/questions/25859069/using-pinchgesture-how-can-i-zoom-in-to-where-a-users-fingers-actually-pinch

**Comment by cloudwu** [comment]
做一点简单的运算就可以了. 你是想把一个 TST 变成一个 ST (这个里没有R)
就是把 `(a+b)*c+d` 变成  `(a*c)+D`. 用一点简单的代数知识就能搞定. (不就是 `a*c + b*c + d` 吗?)

**Comment by czlc** [comment]
3Q
