### ISSUE TITLE
请问ejoy2d是否打算支持mesh

### ISSUE THREAD

**Issue by czlc** [ejoy/ejoy2d#97]
有些2d编辑器支持多边形变形达到一些效果(比如云风之前说的coc那根魔法锅里面的棍子有可能就是这么实现的，它只用了一张图)，比如 http://zh.esotericsoftware.com/spine-meshes

1.不知道ejoy2d是否有计划支持mesh。
2.如果暂时没打算不知各位有没有实现的建议，如果按现在资源格式设计，每一帧都定义此帧的mesh变化，数据量就太大了，动态计算插值要适配原框架要注意些什么问题？

**Comment by cloudwu** [comment]
为什么按现在的资源格式数据量就大了？没多大吧。

发自我的 iPhone

**Comment by czlc** [comment]
一个部件上可能会布局多个顶点，看spine的例子，一只恐龙躯干多达几十个顶点。

**Comment by cloudwu** [comment]
资源里一直支持多边形。

发自我的 iPhone

**Comment by czlc** [comment]
但是每一帧都描述每一个顶点的变化，这样数据就比较大了吧。如果一个部件的所有顶点一起变化那就和现在一样用一个矩阵可以描述，但是mesh是部件中每个顶点都可以单独变化。

**Comment by cloudwu** [comment]
给个具体数据说一下有多少字节.

**Comment by czlc** [comment]
https://gist.github.com/czlc/f3ed5deb632c3587a749
如果按此恐龙躯干85个顶点算的话，每一帧变化的快照就是85 \* 2 \* 4字节。

恐龙图片：
http://zh.esotericsoftware.com/img/spine-user-guide/meshes/bend.png

**Comment by cloudwu** [comment]
那就核算整套动画下来全部数据量有多少, 评估一下是否在可接受范围内.

**Comment by czlc** [comment]
算上不同动作和其它部件不考虑换装应该能控制到500K以内一个。
