### ISSUE TITLE
绘制poly错误

### ISSUE THREAD

**Issue by czlc** [ejoy/ejoy2d#99]
userdata中打包的是struct pack_polygon_data类型，new sprite的时候却存为struct pack_polygon类型供之后操作。

**Comment by cloudwu** [comment]
谢谢, 请看看 patch :)

**Comment by czlc** [comment]
好快啊，我刚刚也改了一个版本，还没来得及pull，是在sprite最后的data union中添加了一个struct pack_polygon *polygon，然后它指向pack_polygon_data中的数据，这样大部分接口就不用变了。
https://gist.github.com/czlc/fe4a4694bb885c73b06b

**Comment by czlc** [comment]
看代码貌似多边形只支持FAN结构

**Comment by cloudwu** [comment]
对的.
